// ESLint flat config (ESLint 10) for the LiteAPI frontend — US-004.
//
// Baseline measured against the full recommended presets
// (@eslint/js + typescript-eslint + eslint-plugin-svelte) on 2026-07-25: 200 findings.
// Every rule that was clean stays enabled. Rules that fired are either fixed in code or
// disabled *explicitly below* with their measured count and the story that will retire them.
// Nothing is silenced with a repo-wide eslint-disable or a --max-warnings fudge.
//
// NOTE ON ACCESSIBILITY: eslint-plugin-svelte v3 ships **zero** `svelte/a11y-*` rules — they
// were removed upstream in v3 and a11y is now reported by the Svelte compiler itself. So a11y
// coverage here comes from `svelte/valid-compile` (enabled below), which surfaces the compiler's
// a11y warnings as lint errors, plus `npm run check` (svelte-check). No a11y rule is weakened;
// the focus traps, `inert` modal blocking and roving tabindex in App.svelte (§2.2) are untouched.

import js from '@eslint/js';
import globals from 'globals';
import svelte from 'eslint-plugin-svelte';
import tseslint from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

export default tseslint.config(
  {
    // Build output and vendored/generated code. `wailsjs/` is generated by Wails and must
    // never be linted or edited.
    ignores: ['dist/**', 'node_modules/**', 'wailsjs/**', 'build/**'],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...svelte.configs.recommended,

  {
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.es2024 },
    },
  },

  {
    files: ['**/*.svelte', '**/*.svelte.ts'],
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
        svelteConfig,
      },
    },
    rules: {
      // Surfaces Svelte compiler warnings (including all a11y warnings) as lint errors.
      // Clean today, and it is the only a11y net the plugin still offers — see header note.
      'svelte/valid-compile': 'error',
    },
  },

  {
    // ── Rules disabled repo-wide, each with its measured violation count and owning story ──
    rules: {
      // 20 violations, all in App.svelte (:974, :1171, :1445, :1449, :5145-:5186).
      // Heuristic rule aimed at the pre-runes `$:` model; these are `$:` blocks that call
      // async functions which reassign variables the block reads. Retired by US-029
      // "Runes — App.svelte", which converts all 110 `$:` statements to runes.
      'svelte/infinite-reactive-loop': 'off',

      // 9 violations (App.svelte :381, :1564, :2017, :3153, :7499, :7719;
      // CodeEditor :18, :218; ResponseInspector :2).
      // Wants SvelteMap/SvelteSet, which are runes-mode reactive collections. Adopting them
      // in pre-runes code would be wrong. Re-enable after US-027/US-028/US-029 land runes.
      'svelte/prefer-svelte-reactivity': 'off',

      // 21 violations, all in App.svelte. This rule cannot see that a `$:` block re-runs, so
      // it reports the memo guards that make those blocks terminate — e.g. `hydratedActiveTabID`
      // (:959) and `lastPresetKey` (:1135), where deleting the flagged assignment would cause
      // an infinite reactive loop. It also flags the pre-hydration initialisers at :480-:481,
      // :509 and :553-:555 that a later `$:` overwrites. Actively unsafe against the pre-runes
      // reactive model; reassess after US-029.
      'no-useless-assignment': 'off',

      // 9 violations (App.svelte :737-:741 and :7317-:7320, response.ts :124).
      // All are deliberate control-character handling: Windows-illegal filename sanitisers
      // (`\x00-\x1F`) and ANSI/OSC escape stripping for terminal output (`\x1B`). The control
      // characters are the point of these regexes, so the rule has no signal here.
      'no-control-regex': 'off',
    },
  },

  {
    // `_`-prefixed bindings are the deliberate-discard convention, used here by the
    // object-rest deletions in App.svelte (`const { [id]: _removed, ...rest } = ...`).
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
        ignoreRestSiblings: true,
      }],
    },
  },

  {
    files: ['src/App.svelte'],
    rules: {
      // 21 violations, confined to this file (every other file is clean, so the rule stays
      // an error everywhere else). These are NOT cosmetic — they are evidence of unwired
      // features, and deleting them would destroy that evidence:
      //   * write-only backend results, computed but never rendered: `exportText` (:419),
      //     `gitVersionText` (:503), `gitCloneOutput` (:504), `shareCollectionResult` (:508),
      //     `generateDocsResult` (:549);
      //   * never-called action handlers whose Wails bindings do exist: `openCollection`
      //     (:4074), `connectGitRemote` (:4427), `openSelectedGitCollections` (:5321),
      //     `toggleGitCandidate` (:5332);
      //   * dead body-textarea scroll sync: `bodyTextScrollLeft`/`Top` (:588-:589) with
      //     `updateBodyText` (:1861) and `syncBodyTextScroll` (:1868);
      //   * unused imports `VariableTextOverlay` (:7) and `ImportCollection` (:97), plus
      //     `responseExampleDraft` (:2351) and `hexFromBase64` (:7477).
      // Owned by US-025 "Extract modals", which pulls these modal bodies out and will either
      // wire the results up or delete them deliberately.
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },

  {
    files: ['test/**/*.mts', '**/*.config.{js,ts}'],
    languageOptions: { globals: { ...globals.node } },
  },
);
