package transport

import (
	"strings"
	"testing"
)

// decryptPEMKeyIfNeeded sat at 21.4%. It is what lets a user load a client
// certificate whose private key is encrypted -- the feature .golangci.yml
// carries a standing exclusion for, because Go deprecated RFC-1423 without
// providing a replacement and refusing such keys would drop something that
// works.
//
// The fixture below is a STATIC legacy-format key rather than one generated by
// calling x509.EncryptPEMBlock from the test. Two reasons: the deprecated API
// stays confined to the one file the lint exclusion names, and a fixed sample
// is a truer test of the feature, which exists to read keys that ALREADY EXIST
// on disk in exactly this format.
//
// Generated once for this test with a throwaway 2048-bit RSA key. It protects
// nothing.

const encryptedKeyPassphrase = "test-passphrase"

const encryptedKeyPEM = `-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-256-CBC,49cc38482758f3dde70cf9e9303b7257

oK/NH4UM6UrVgUaB64P+FAmH7J96iiWOxuPIkRJDy6I8mwC8Wv/mDeROu1K/0zus
UbAWWOLj4zkFXfZOuHDdupxwHR2isd7hdzmv944/vgDDyksOkkCz3IH9Db9EZ8F3
bAEU/6+y1ff/xNmUI1kweI21wnAAg8cgtL27Exoiy6Xcdg/WrhS+yqQPTVt6a8Uy
P1czj/TbgaLnI35EGFnqT/MVGVXfA6ZC52cxcJkGKz5CmkNBCT5B9tdb3tXKNOty
5C/ZqQTmDz6OHXDoYeyJxP/AHqRpk5fEHvlBPoc4gIeCrC32pX6wUPv1fX3UdwWs
LOM1A4Cf2p0LdcGQZOCkerU9eV/jqcCva6e/1fNDBMzK9q4AAb7Km0uE9f61tKdr
4jLuBpxkrSR2xv1gsCVDppDjf6YLOBfDL+CV622OzZU5Q9UNDy6FiXD/MXWlhfYD
Pnt4vE+ZyrC1oJknLzUoAO4hmuHBgFPzYeE1Xj0wL4a7fnnXnyqJTprltyDURLBO
6O59tqNzYiBuPc6YrPlWU6s9cPjLy72FHf5QFUGQ5AmRjwHCl8Gs+IXWkW4QsHTq
To5zhlt6rwyD2zrxQpelaqbDJHZzXPbSsB8ThPQEEdxXxeFiyyBBukKAFNvqGiml
I+I9quott5kX5netl+QmKFUsiyH4tqSwgoytLvnmPAgLpAa6IGa5f7mhSo7okaYZ
jjoM8fDt9yNma2pIoKSE0mk5AXdv6J5FG9i+2IC1zAjmJWMq1eeNxaV+idcSlHVO
bEmxBH1Min2u0F/RRGG3E9fsadLK+oC5HlMimsZdvZ7xY0xFk5iNJH/M3V6IvFND
wc+7oFbubPlPg9QlCh0/U5vOxidxX9MP4qD9wzM9C1kCdHCDTH+azXayZCBwdmw1
9HPbDaEya4KPE0ZIS4iyg+4UzC2uXin/5z8DWAE0Hps29nTzt0lKCV26hpETmHw5
JPruDFwTbw82kBc632JSrkWpWD1UIRAbpabeiEN00gW1wKAFTmkuSecpUcVoly3J
A/BjwvLbTwsKzAUvQ9PJNVU6u/EV2qzu9LTcV1Pv/wdZdDnWX5BUCpYF0jmWdr9y
pj7oFE3FNch7+ndTlF7JLZYxcfcQt8G+S+SodHcvxXnDNjfBFDHRbfyuFE9Dj4cD
cTxpKrzOBPGBKIn5m8bLb85wVJ2wufRVfFvafoiDZ+i5jCFx3h+hewHueYr/osLY
0P5CA2Oxcxdj8/PtnbRbJwFS9pXle8pFO5ucGt0KhGF9uvIxIW8mCDMoLS4Ck1BX
pgm9PTF9fKOHcLtHGBLYYz8MaYysU5hhn1Oq+Q9NVnJkuPPJi2q5V+Vk8soynSG9
m78KybtdWUycV2vTt3hv+xUZtsZAFkjm/MrrZ+f+L1G8zDKsYHrx+nMLVT5vZjCx
O+70x72EHpE+d3wy65MaUXbxJiDfRXVUYt3fdag8u07nLPLTASMHmRDvGf64ENkV
5CIOdRiIckura6fLR5bf/+wt7CS7uH6rw5IqiUXX7x2BbH+LwOO36pxR2vtgiIH2
dY7u8pyBmcLua3uI7aqHiS0XpC7aHXF08YWnpDCiAKXYvV3ReXYG4XbgsDcpXfXT
-----END RSA PRIVATE KEY-----
`

const plainKeyPEM = `-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAmctW1U89cK2aZFqa5Ny3lv7pzf+KLzIvmdFWipdumbsiPamH
SzIGKT76YooFlvCYaTqqlhMfY1KdSiECCt4vGHBfrGGRD7xghDKouPyRWB3XQW2Q
wQNPCfwJ0n7LRcZbOGgBWZnzb8w8aWk00HTch9VnMSBhqdY6sY6DyK5QtEJ++Kzw
gwighxMqMzYGu2eYNfsrPAVNQtHZt3iHBT88rz0wIoGLovTYI5bhwQK7GYozISPc
ojQEOthR1/3vL8m7EHQXvZ1pWCc14vTuC77NiaIeaBjvhQID9jZv658tl/BLCLq8
91cDaZbA6zSMxSkGamprJbHETEZGfliTB4dYOwIDAQABAoIBABmuTiwlZLWNj6Pl
S0sfHhr9Kw6Gds0lvLQbNC/FVKcgC/ou9lQUoNm/VfEhagiH2XNs4/JWdB3SPEiW
FXC6JDQZA6jVy/LMOnOov+rP5fdIWFrpEExioI6iwwMewBPBKRdUqrELF47aFFZn
xnVupiqadHZMGXLSPo/Ko+/dR8WpuKGxvLrpt3CZn9LKB1NnHruW0k8m/MANqDkd
sIo+m6+HczqAZWlTCCGHe5MBGiih7zWyh0Oe1zDbV2b+py7Rr9LzYDRBN8fw4INM
GcfdFDj1uneaFsd4mZB5RCqDqtGzKOfmD4wqX8E+5OfjTzk1drksEK6K6wmBym4s
hGAfX/ECgYEAwrJpruziMRlFEqNK4LQhVhg+YOY6Ll0K6OtHNVQ+Deve9bK7Euvn
T1md7MAStikqTMJ9yKd5uc/SlqshIHUxJZzWP7wZAkoKzUYgv80DYFqG/GtjbVzs
LzTfAjnDSfsq8lV+faVaMnGTFBFjV6UwCHC2LYtC7OmWvUOHYjG1KtECgYEAyjf2
Br/6VNjibBgpguNYIJPbyc81DsFqQGWv5PN+09Tx1NGu6r0N8dtNz/MbtqA0fIOL
oh9tve1v28zqUxAll72se+2xjMu634O5wa309ZNGhD3AaYu95Xq768mbSycC+Pmg
E+XVGNczzXE1/j6o4n9ORkSOLJuF0Pn/KBhAPUsCgYEAiMmIbpmHIS+706heBxkH
AtHtoW6fGcvMym/ii5kwL9+zubNks5qB3MH9rkQT4V9ylJNghAUGBIH6VljM4Vz0
tpRGAmlIuM8EX8wRXi/PW3a+t8FLDZ7nYRMoSwwCJIwOVEu0ntn5UM9yofrFbOJl
qMhndgANeR10BmzXRSnfOsECgYB/jdsPmOsTuBbirj8JA9SkAABEhQJnw1L9OedA
mOMoRYshff5CrWvtYjLr9+JESTuyStu6MO7tPacwU0p/iJDd7VOufFlhgWTn9lQm
uk7o1LRHWBhVu0LWTJva+DmPpxT17aeuxWuslppjfYTcUbP/4uOB6V5w/szi676q
ENn8jwKBgE5ZloCWcNoKKR3yUF1TbdJfcQTRXwOKbAiAKeS0Pnb3spU/ZNLQnCex
n5lg7sz58s800ZJeAGa932jsuNdbpLvMjkweGlxuuzUQ5IdjCIn3rT2/mhxtFEDT
dnC8TtOGOP0RvirKcyYBGr0DkA5X3kat8DgdO+WeDkPLlfO4TbFG
-----END RSA PRIVATE KEY-----
`

// An unencrypted key is returned byte-for-byte. Re-encoding it would reorder or
// reflow a file the user supplied, and for a key that is also a chain that means
// changing bytes nobody asked to change.
func TestAnUnencryptedKeyIsReturnedUnchanged(t *testing.T) {
	out, err := decryptPEMKeyIfNeeded([]byte(plainKeyPEM), "")
	if err != nil {
		t.Fatal(err)
	}
	if string(out) != plainKeyPEM {
		t.Error("an unencrypted key was rewritten")
	}

	// And a passphrase supplied for a key that does not need one is ignored
	// rather than treated as an error.
	out, err = decryptPEMKeyIfNeeded([]byte(plainKeyPEM), "unnecessary")
	if err != nil {
		t.Fatal(err)
	}
	if string(out) != plainKeyPEM {
		t.Error("a spurious passphrase altered an unencrypted key")
	}

	// A key file that also carries its chain must come back WHOLE. Comparing
	// only a bare key cannot catch a re-encode, because a canonically formatted
	// block re-encodes to itself byte for byte — the trailer is what makes the
	// difference observable.
	combined := plainKeyPEM + "-----BEGIN CERTIFICATE-----\nZm9v\n-----END CERTIFICATE-----\n"
	out, err = decryptPEMKeyIfNeeded([]byte(combined), "")
	if err != nil {
		t.Fatal(err)
	}
	if string(out) != combined {
		t.Errorf("an unencrypted key file was rewritten and lost its trailer:\n%s", out)
	}
}

func TestAnEncryptedKeyIsDecryptedWithItsPassphrase(t *testing.T) {
	out, err := decryptPEMKeyIfNeeded([]byte(encryptedKeyPEM), encryptedKeyPassphrase)
	if err != nil {
		t.Fatalf("decrypt: %v", err)
	}
	if strings.Contains(string(out), "Proc-Type") || strings.Contains(string(out), "DEK-Info") {
		t.Error("the decrypted key still carries the encryption headers")
	}
	if !strings.Contains(string(out), "BEGIN RSA PRIVATE KEY") {
		t.Errorf("the result is not a PEM key:\n%s", out)
	}
}

// A wrong passphrase must FAIL rather than return something unusable. Returning
// the encrypted bytes would push the failure into tls.X509KeyPair, which reports
// a parse error naming neither the certificate nor the passphrase.
func TestAWrongPassphraseIsAnError(t *testing.T) {
	_, err := decryptPEMKeyIfNeeded([]byte(encryptedKeyPEM), "wrong")
	if err == nil {
		t.Fatal("a wrong passphrase was accepted")
	}
	if !strings.Contains(err.Error(), "decrypt client certificate key") {
		t.Errorf("error does not name the operation: %v", err)
	}
}

// An encrypted key with NO passphrase is an error.
//
// This test previously asserted the OPPOSITE, on the reasoning that the user
// might not have configured a passphrase yet and the TLS layer was the right
// place for that to surface. It is not: tls.X509KeyPair receives the still-
// encrypted bytes and reports "failed to find any PEM data" or a generic ASN.1
// parse failure, which names neither encryption nor the passphrase field the
// user needs to fill in. The information about WHY the key cannot be read
// exists only here, so the error has to be raised here.
func TestAnEncryptedKeyWithNoPassphraseIsAnError(t *testing.T) {
	_, err := decryptPEMKeyIfNeeded([]byte(encryptedKeyPEM), "")
	if err == nil {
		t.Fatal("an encrypted key with no passphrase was accepted; the failure would surface later as an unexplained parse error")
	}
	// The message has to name both the cause and the missing input, because it
	// is the only thing the user sees.
	for _, want := range []string{"encrypted", "passphrase"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error %q does not mention %q", err, want)
		}
	}
}

// An encrypted PKCS#8 key ("BEGIN ENCRYPTED PRIVATE KEY") is the modern format
// openssl produces by default, and the one this code CANNOT decrypt: it carries
// no Proc-Type header, so x509.IsEncryptedPEMBlock returns false and the block
// used to be handed to tls.X509KeyPair as though it were plaintext.
//
// Being unable to decrypt it is acceptable; being unable to say so is not. The
// error names the format and gives the exact command that fixes it, because
// "unsupported" without a remedy leaves the user with no next step.
func TestAnEncryptedPKCS8KeyIsRejectedWithAConversionHint(t *testing.T) {
	// Body bytes are irrelevant — detection is by block type, and that is the
	// point: nothing here needs to parse for the error to be correct.
	const pkcs8EncryptedPEM = `-----BEGIN ENCRYPTED PRIVATE KEY-----
MIIFHDBOBgkqhkiG9w0BBQ0wQTApBgkqhkiG9w0BBQwwHAQIkT7CbaTgLmECAggA
MAwGCCqGSIb3DQIJBQAwFAYIKoZIhvcNAwcECHl6ZXJvZm9v
-----END ENCRYPTED PRIVATE KEY-----
`
	_, err := decryptPEMKeyIfNeeded([]byte(pkcs8EncryptedPEM), "test-passphrase")
	if err == nil {
		t.Fatal("an encrypted PKCS#8 key was accepted and would fail later with an unrelated parse error")
	}
	for _, want := range []string{"PKCS#8", "openssl pkcs8 -topk8 -nocrypt"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error %q does not mention %q", err, want)
		}
	}

	// Rejected regardless of whether a passphrase was supplied: the format is
	// what is unsupported, so a correct passphrase does not change the answer
	// and must not produce a different, more confusing message.
	if _, err := decryptPEMKeyIfNeeded([]byte(pkcs8EncryptedPEM), ""); err == nil {
		t.Error("an encrypted PKCS#8 key with no passphrase was accepted")
	}
}

// An UNENCRYPTED PKCS#8 key ("BEGIN PRIVATE KEY") is the common case and must
// keep working untouched — the new block-type check keys on "ENCRYPTED PRIVATE
// KEY", and a substring match on "PRIVATE KEY" would reject every ordinary
// PKCS#8 key in existence.
func TestAnUnencryptedPKCS8KeyIsUnaffected(t *testing.T) {
	const pkcs8PlainPEM = `-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZy1bVTz1wrZpk
-----END PRIVATE KEY-----
`
	out, err := decryptPEMKeyIfNeeded([]byte(pkcs8PlainPEM), "")
	if err != nil {
		t.Fatalf("an unencrypted PKCS#8 key was rejected: %v", err)
	}
	if string(out) != pkcs8PlainPEM {
		t.Error("an unencrypted PKCS#8 key was rewritten")
	}
}

// THE PART THAT IS EASY TO DROP. A key file often holds the key AND the
// certificate chain after it. Only the first block is decrypted, and everything
// following it must be carried through — losing `rest` silently discards the
// chain, and the connection then fails verification for a reason nothing in the
// UI can explain.
func TestBytesAfterTheKeyBlockAreCarriedThrough(t *testing.T) {
	const trailer = "-----BEGIN CERTIFICATE-----\nZm9v\n-----END CERTIFICATE-----\n"
	combined := encryptedKeyPEM + trailer

	out, err := decryptPEMKeyIfNeeded([]byte(combined), encryptedKeyPassphrase)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(out), "BEGIN CERTIFICATE") {
		t.Errorf("the certificate following the key was dropped:\n%s", out)
	}
	if !strings.Contains(string(out), "BEGIN RSA PRIVATE KEY") {
		t.Error("the key itself was lost")
	}
}

// Input that is not PEM at all comes back unchanged rather than erroring. The
// caller passes whatever the user pointed at, and a clearer failure comes from
// the certificate loader that knows what it expected.
func TestNonPEMInputIsReturnedUnchanged(t *testing.T) {
	for _, input := range []string{"", "not pem at all", "-----BEGIN GARBAGE-----"} {
		out, err := decryptPEMKeyIfNeeded([]byte(input), "pass")
		if err != nil {
			t.Errorf("%q: %v", input, err)
		}
		if string(out) != input {
			t.Errorf("%q became %q", input, out)
		}
	}
}
