// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCookieFromHeader(arg1:string,arg2:string):Promise<main.AppState>;

export function ApplyCollectionImport(arg1:main.CollectionImportApplyRequest):Promise<main.CollectionImportApplyResult>;

export function ApplyOpenAPILocalDrift(arg1:string,arg2:main.OpenAPILocalDriftOptions):Promise<main.AppState>;

export function ApplyOpenAPISync(arg1:string,arg2:main.OpenAPISyncOptions):Promise<main.AppState>;

export function CancelCollectionRun(arg1:string):Promise<boolean>;

export function CancelGRPCStream(arg1:string,arg2:string):Promise<main.AppState>;

export function CancelRequest(arg1:string,arg2:string):Promise<boolean>;

export function CheckOpenAPILocalDrift(arg1:string):Promise<main.OpenAPILocalDriftResult>;

export function CheckOpenAPISync(arg1:string,arg2:main.OpenAPISyncOptions):Promise<main.OpenAPISyncResult>;

export function CheckOpenAPIUpdates(arg1:string):Promise<main.OpenAPISyncUpdateCheckResult>;

export function CheckoutCollectionGitBranch(arg1:string,arg2:string):Promise<main.CollectionGitOperationResult>;

export function ChooseCollectionImportFiles():Promise<main.CollectionImportPickerResult>;

export function ChooseCollectionImportFolder():Promise<main.CollectionImportPickerResult>;

export function ClearCookies():Promise<main.AppState>;

export function ClearDomainCookies(arg1:string):Promise<main.AppState>;

export function ClearFileCache():Promise<number>;

export function ClearNotifications():Promise<main.AppState>;

export function ClearSSLSessionCache():Promise<main.AppState>;

export function CloneCollection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.AppState>;

export function CloneFolder(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.AppState>;

export function CloneGitRepository(arg1:string,arg2:string,arg3:string):Promise<main.GitCloneResult>;

export function CloneRequest(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.AppState>;

export function CloneResponseExample(arg1:string,arg2:string,arg3:string):Promise<main.AppState>;

export function CloseAllTabs():Promise<main.AppState>;

export function CloseTab(arg1:string):Promise<main.AppState>;

export function CodeGenerationTargets():Promise<Array<main.CodeGenerationTarget>>;

export function CommitCollectionGit(arg1:string,arg2:string):Promise<main.CollectionGitOperationResult>;

export function CompleteOAuth2Callback(arg1:string):Promise<boolean>;

export function ConnectCollectionGitRemote(arg1:string,arg2:string):Promise<main.AppState>;

export function ConnectGRPCStream(arg1:string,arg2:string,arg3:string):Promise<main.AppState>;

export function ConnectGRPCStreamWithPromptValues(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<main.AppState>;

export function ConnectOpenAPISync(arg1:string,arg2:main.OpenAPISyncOptions):Promise<main.AppState>;

export function ConnectWebSocket(arg1:string,arg2:string,arg3:string):Promise<main.AppState>;

export function ConnectWebSocketWithPromptValues(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<main.AppState>;

export function CopyGlobalEnvironment(arg1:string,arg2:string):Promise<main.AppState>;

export function CopyGlobalEnvironmentAs(arg1:string,arg2:string,arg3:string):Promise<main.AppState>;

export function CreateCollection(arg1:string,arg2:string,arg3:string):Promise<main.AppState>;

export function CreateCollectionGitBranch(arg1:string,arg2:string,arg3:boolean):Promise<main.CollectionGitOperationResult>;

export function CreateEnvironment(arg1:string,arg2:string):Promise<main.AppState>;

export function CreateFolder(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.AppState>;

export function CreateGlobalEnvironment(arg1:string,arg2:string):Promise<main.AppState>;

export function CreateRequest(arg1:string,arg2:string,arg3:string):Promise<main.AppState>;

export function CreateResponseExample(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.AppState>;

export function CreateTerminalSession(arg1:string):Promise<main.TerminalSession>;

export function CreateWorkspace(arg1:string):Promise<main.AppState>;

export function DeleteCookie(arg1:string):Promise<main.AppState>;

export function DeleteDotEnvFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<main.DotEnvFile>>;

export function DeleteFolder(arg1:string,arg2:string):Promise<main.AppState>;

export function DeleteFolderRecoverable(arg1:string,arg2:string):Promise<main.RecoverableDeleteResult>;

export function DeleteGlobalEnvironment(arg1:string,arg2:string):Promise<main.AppState>;

export function DeleteRequest(arg1:string,arg2:string):Promise<main.AppState>;

export function DeleteRequestRecoverable(arg1:string,arg2:string):Promise<main.RecoverableDeleteResult>;

export function DeleteResponseExample(arg1:string,arg2:string,arg3:string):Promise<main.AppState>;

export function DiscardRecoveryEntry(arg1:string):Promise<boolean>;

export function DiscardRequestDraft(arg1:string,arg2:string):Promise<main.AppState>;

export function DiscardUnsavedDrafts(arg1:Array<main.UnsavedDraft>):Promise<main.AppState>;

export function DisconnectCollectionGitRemote(arg1:string):Promise<main.AppState>;

export function DisconnectOpenAPISync(arg1:string):Promise<main.AppState>;

export function DisconnectWebSocket(arg1:string,arg2:string):Promise<main.AppState>;

export function EndGRPCStream(arg1:string,arg2:string):Promise<main.AppState>;

export function ExportCollection(arg1:string):Promise<string>;

export function ExportCollectionWithOptions(arg1:string,arg2:main.CollectionExportOptions):Promise<main.CollectionExportResult>;

export function ExportGlobalEnvironment(arg1:string,arg2:string):Promise<string>;

export function ExportGlobalEnvironments(arg1:string,arg2:Array<string>,arg3:string):Promise<main.GlobalEnvironmentExportResult>;

export function FetchCollectionGit(arg1:string,arg2:string):Promise<main.CollectionGitOperationResult>;

export function FlushPendingWrites():Promise<void>;

export function GenerateCollectionDocs(arg1:string,arg2:main.GenerateCollectionDocsOptions):Promise<main.GenerateCollectionDocsResult>;

export function GenerateGRPCMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GenerateGrpcurlCommand(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateRequestCode(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GenerateResponseExampleCode(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetCollectionGitDiff(arg1:string,arg2:string,arg3:boolean):Promise<main.CollectionGitDiff>;

export function GetCollectionGitStatus(arg1:string):Promise<main.CollectionGitSnapshot>;

export function GetDevToolsSnapshot():Promise<main.DevToolsSnapshot>;

export function GetFileCacheSize():Promise<number>;

export function GetOpenAPISyncSpec(arg1:string):Promise<main.OpenAPISyncSpecViewResult>;

export function GetOpenAPISyncSpecDiff(arg1:string,arg2:main.OpenAPISyncOptions):Promise<main.OpenAPISyncSpecDiffResult>;

export function GetState():Promise<main.AppState>;

export function GetTerminalSession(arg1:string):Promise<main.TerminalSession>;

export function GetWebStorageScope():Promise<string>;

export function GitVersion():Promise<string>;

export function ImportCollection(arg1:string,arg2:main.ImportPayload):Promise<main.AppState>;

export function ImportGlobalEnvironment(arg1:string,arg2:string):Promise<main.AppState>;

export function InitializeCollectionGit(arg1:string):Promise<main.CollectionGitOperationResult>;

export function KillTerminalSession(arg1:string):Promise<void>;

export function ListDotEnvFiles(arg1:string,arg2:string):Promise<Array<main.DotEnvFile>>;

export function ListGRPCMethods(arg1:string,arg2:string,arg3:string):Promise<Array<main.GRPCMethodInfo>>;

export function ListRecoveryEntries():Promise<Array<main.RecoveryEntry>>;

export function ListTerminalSessions():Promise<Array<main.TerminalSession>>;

export function ListUnsavedDrafts():Promise<Array<main.UnsavedDraft>>;

export function ListWorkspaceWindowTargets():Promise<Array<main.WorkspaceWindowTarget>>;

export function MarkAllNotificationsRead():Promise<main.AppState>;

export function MarkNotificationRead(arg1:string):Promise<main.AppState>;

export function MoveOpenTab(arg1:string,arg2:number):Promise<main.AppState>;

export function MoveOpenTabNarrow(arg1:string,arg2:number):Promise<main.TabsMutation>;

export function OpenCollection(arg1:string,arg2:string):Promise<main.AppState>;

export function OpenGitCollections(arg1:string,arg2:Array<string>,arg3:string):Promise<main.AppState>;

export function OpenNewWindow():Promise<main.WorkspaceWindowTarget>;

export function OpenRequestTab(arg1:string,arg2:string):Promise<main.AppState>;

export function OpenResponseExampleTab(arg1:string,arg2:string,arg3:string):Promise<main.AppState>;

export function OpenWorkspaceInNewWindow(arg1:string):Promise<main.WorkspaceWindowTarget>;

export function ParseBru(arg1:string):Promise<main.RequestItem>;

export function PreviewCollectionImport(arg1:main.CollectionImportPreviewRequest):Promise<main.CollectionImportPreview>;

export function PullCollectionGit(arg1:string,arg2:string,arg3:string):Promise<main.CollectionGitOperationResult>;

export function PushCollectionGit(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.CollectionGitOperationResult>;

export function ReadResponseBody(arg1:string,arg2:number,arg3:number):Promise<main.ResponseBodySlice>;

export function RefreshChangedCollections():Promise<main.CollectionWatchRefreshResult>;

export function RefreshCollection(arg1:string):Promise<main.AppState>;

export function RemoveCollection(arg1:string):Promise<main.AppState>;

export function RemoveCollectionRecoverable(arg1:string):Promise<main.RecoverableDeleteResult>;

export function RenameCollection(arg1:string,arg2:string):Promise<main.AppState>;

export function RenameFolder(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.AppState>;

export function RenameRequest(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.AppState>;

export function RenameResponseExample(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.AppState>;

export function ReopenLastClosedTab(arg1:string):Promise<main.AppState>;

export function ResetDemoData():Promise<main.AppState>;

export function ResizeTerminalSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveCollectionFolderPath(arg1:string,arg2:string):Promise<string>;

export function ResolveProcessEnvValues(arg1:string,arg2:Array<string>):Promise<Record<string, string>>;

export function RestoreRecoveryEntry(arg1:string):Promise<main.AppState>;

export function RevealCollectionFolderInFolder(arg1:string,arg2:string):Promise<void>;

export function RevealCollectionInFolder(arg1:string):Promise<void>;

export function RevealRequestInFolder(arg1:string,arg2:string):Promise<void>;

export function RunCollection(arg1:string,arg2:string):Promise<main.AppState>;

export function RunCollectionWithOptions(arg1:string,arg2:string,arg3:main.RunnerOptions):Promise<main.AppState>;

export function SaveAllTabs(arg1:string):Promise<main.AppState>;

export function SaveCollectionExport(arg1:string,arg2:main.CollectionExportOptions,arg3:string):Promise<main.CollectionSaveResult>;

export function SaveCookie(arg1:main.CookieInput):Promise<main.AppState>;

export function SaveDotEnvFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<main.DotEnvFile>>;

export function SaveGlobalEnvironmentExport(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<main.GlobalEnvironmentSaveResult>;

export function SaveRequest(arg1:string,arg2:string):Promise<main.AppState>;

export function SaveResponseBody(arg1:string,arg2:string,arg3:string):Promise<main.ResponseBodySaveResult>;

export function SaveResponseExample(arg1:string,arg2:string,arg3:string):Promise<main.AppState>;

export function SaveResponseTimeline(arg1:string,arg2:string,arg3:string):Promise<main.ResponseTimelineSaveResult>;

export function SaveUnsavedDrafts(arg1:Array<main.UnsavedDraft>):Promise<main.AppState>;

export function ScanGitCollections(arg1:string):Promise<Array<main.GitCollectionCandidate>>;

export function SelectCustomCaCertificate():Promise<string>;

export function SelectDefaultLocation():Promise<string>;

export function SelectRunnerDataFile():Promise<string>;

export function SendGRPCStreamMessage(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.AppState>;

export function SendGRPCStreamMessageWithPromptValues(arg1:string,arg2:string,arg3:string,arg4:number,arg5:Record<string, string>):Promise<main.AppState>;

export function SendRequest(arg1:string,arg2:string,arg3:string):Promise<main.AppState>;

export function SendRequestWithPromptValues(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<main.AppState>;

export function SendWebSocketMessage(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.AppState>;

export function SendWebSocketMessageWithPromptValues(arg1:string,arg2:string,arg3:string,arg4:number,arg5:Record<string, string>):Promise<main.AppState>;

export function SetActiveGlobalEnvironment(arg1:string,arg2:string):Promise<main.AppState>;

export function SetActiveTab(arg1:string):Promise<main.AppState>;

export function SetActiveTabNarrow(arg1:string):Promise<main.TabsMutation>;

export function SetActiveWorkspace(arg1:string):Promise<main.AppState>;

export function SetCollectionGitRemote(arg1:string,arg2:string,arg3:string):Promise<main.CollectionGitOperationResult>;

export function StageCollectionGitPaths(arg1:string,arg2:Array<string>):Promise<main.CollectionGitOperationResult>;

export function StringifyBru(arg1:main.RequestItem):Promise<string>;

export function UnstageCollectionGitPaths(arg1:string,arg2:Array<string>):Promise<main.CollectionGitOperationResult>;

export function UpdateCollectionAuth(arg1:string,arg2:main.AuthConfig):Promise<main.AppState>;

export function UpdateCollectionClientCertificates(arg1:string,arg2:Array<main.ClientCertificateConfig>):Promise<main.AppState>;

export function UpdateCollectionDocs(arg1:string,arg2:string):Promise<main.AppState>;

export function UpdateCollectionHeaders(arg1:string,arg2:Array<main.KeyValue>):Promise<main.AppState>;

export function UpdateCollectionPresets(arg1:string,arg2:main.CollectionPresets):Promise<main.AppState>;

export function UpdateCollectionProtobuf(arg1:string,arg2:main.CollectionProtobufConfig):Promise<main.AppState>;

export function UpdateCollectionProxy(arg1:string,arg2:main.ProxyConfig):Promise<main.AppState>;

export function UpdateCollectionScripts(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.AppState>;

export function UpdateCollectionSecurityConfig(arg1:string,arg2:main.CollectionSecurityConfig):Promise<main.AppState>;

export function UpdateCollectionVariables(arg1:string,arg2:Array<main.Variable>):Promise<main.AppState>;

export function UpdateEnvironmentVariables(arg1:string,arg2:string,arg3:Array<main.Variable>):Promise<main.AppState>;

export function UpdateFolderSettings(arg1:string,arg2:string,arg3:main.FolderConfig):Promise<main.AppState>;

export function UpdateGlobalEnvironment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.AppState>;

export function UpdateGlobalEnvironmentVariables(arg1:string,arg2:string,arg3:Array<main.Variable>):Promise<main.AppState>;

export function UpdateOpenAPISyncConfig(arg1:string,arg2:main.OpenAPISyncConfig):Promise<main.AppState>;

export function UpdateOpenTabPanes(arg1:string,arg2:string,arg3:string):Promise<main.AppState>;

export function UpdateOpenTabPanesNarrow(arg1:string,arg2:string,arg3:string):Promise<main.TabsMutation>;

export function UpdatePreferences(arg1:main.Preferences):Promise<main.AppState>;

export function UpdateRequest(arg1:string,arg2:string,arg3:main.RequestPatch):Promise<main.AppState>;

export function UpdateRequestNarrow(arg1:string,arg2:string,arg3:main.RequestPatch):Promise<main.RequestMutation>;

export function UpdateResponseExample(arg1:string,arg2:string,arg3:string,arg4:main.ResponseExample):Promise<main.AppState>;

export function WriteTerminalSession(arg1:string,arg2:string):Promise<main.TerminalSession>;
