// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCookieFromHeader(arg1, arg2) {
  return window['go']['main']['App']['AddCookieFromHeader'](arg1, arg2);
}

export function ApplyCollectionImport(arg1) {
  return window['go']['main']['App']['ApplyCollectionImport'](arg1);
}

export function ApplyOpenAPILocalDrift(arg1, arg2) {
  return window['go']['main']['App']['ApplyOpenAPILocalDrift'](arg1, arg2);
}

export function ApplyOpenAPISync(arg1, arg2) {
  return window['go']['main']['App']['ApplyOpenAPISync'](arg1, arg2);
}

export function CancelCollectionRun(arg1) {
  return window['go']['main']['App']['CancelCollectionRun'](arg1);
}

export function CancelGRPCStream(arg1, arg2) {
  return window['go']['main']['App']['CancelGRPCStream'](arg1, arg2);
}

export function CancelRequest(arg1, arg2) {
  return window['go']['main']['App']['CancelRequest'](arg1, arg2);
}

export function CheckOpenAPILocalDrift(arg1) {
  return window['go']['main']['App']['CheckOpenAPILocalDrift'](arg1);
}

export function CheckOpenAPISync(arg1, arg2) {
  return window['go']['main']['App']['CheckOpenAPISync'](arg1, arg2);
}

export function CheckOpenAPIUpdates(arg1) {
  return window['go']['main']['App']['CheckOpenAPIUpdates'](arg1);
}

export function CheckoutCollectionGitBranch(arg1, arg2) {
  return window['go']['main']['App']['CheckoutCollectionGitBranch'](arg1, arg2);
}

export function ChooseCollectionImportFiles() {
  return window['go']['main']['App']['ChooseCollectionImportFiles']();
}

export function ChooseCollectionImportFolder() {
  return window['go']['main']['App']['ChooseCollectionImportFolder']();
}

export function ClearCookies() {
  return window['go']['main']['App']['ClearCookies']();
}

export function ClearDomainCookies(arg1) {
  return window['go']['main']['App']['ClearDomainCookies'](arg1);
}

export function ClearFileCache() {
  return window['go']['main']['App']['ClearFileCache']();
}

export function ClearNotifications() {
  return window['go']['main']['App']['ClearNotifications']();
}

export function ClearSSLSessionCache() {
  return window['go']['main']['App']['ClearSSLSessionCache']();
}

export function CloneCollection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CloneCollection'](arg1, arg2, arg3, arg4);
}

export function CloneFolder(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CloneFolder'](arg1, arg2, arg3, arg4);
}

export function CloneGitRepository(arg1, arg2, arg3) {
  return window['go']['main']['App']['CloneGitRepository'](arg1, arg2, arg3);
}

export function CloneRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CloneRequest'](arg1, arg2, arg3, arg4);
}

export function CloneResponseExample(arg1, arg2, arg3) {
  return window['go']['main']['App']['CloneResponseExample'](arg1, arg2, arg3);
}

export function CloseAllTabs() {
  return window['go']['main']['App']['CloseAllTabs']();
}

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function CodeGenerationTargets() {
  return window['go']['main']['App']['CodeGenerationTargets']();
}

export function CommitCollectionGit(arg1, arg2) {
  return window['go']['main']['App']['CommitCollectionGit'](arg1, arg2);
}

export function CompleteOAuth2Callback(arg1) {
  return window['go']['main']['App']['CompleteOAuth2Callback'](arg1);
}

export function ConnectCollectionGitRemote(arg1, arg2) {
  return window['go']['main']['App']['ConnectCollectionGitRemote'](arg1, arg2);
}

export function ConnectGRPCStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectGRPCStream'](arg1, arg2, arg3);
}

export function ConnectGRPCStreamWithPromptValues(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectGRPCStreamWithPromptValues'](arg1, arg2, arg3, arg4);
}

export function ConnectOpenAPISync(arg1, arg2) {
  return window['go']['main']['App']['ConnectOpenAPISync'](arg1, arg2);
}

export function ConnectWebSocket(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectWebSocket'](arg1, arg2, arg3);
}

export function ConnectWebSocketWithPromptValues(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectWebSocketWithPromptValues'](arg1, arg2, arg3, arg4);
}

export function CopyGlobalEnvironment(arg1, arg2) {
  return window['go']['main']['App']['CopyGlobalEnvironment'](arg1, arg2);
}

export function CopyGlobalEnvironmentAs(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyGlobalEnvironmentAs'](arg1, arg2, arg3);
}

export function CreateCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2, arg3);
}

export function CreateCollectionGitBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCollectionGitBranch'](arg1, arg2, arg3);
}

export function CreateEnvironment(arg1, arg2) {
  return window['go']['main']['App']['CreateEnvironment'](arg1, arg2);
}

export function CreateFolder(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3, arg4);
}

export function CreateGlobalEnvironment(arg1, arg2) {
  return window['go']['main']['App']['CreateGlobalEnvironment'](arg1, arg2);
}

export function CreateRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateRequest'](arg1, arg2, arg3);
}

export function CreateResponseExample(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateResponseExample'](arg1, arg2, arg3, arg4);
}

export function CreateTerminalSession(arg1) {
  return window['go']['main']['App']['CreateTerminalSession'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DeleteCookie(arg1) {
  return window['go']['main']['App']['DeleteCookie'](arg1);
}

export function DeleteDotEnvFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteDotEnvFile'](arg1, arg2, arg3, arg4);
}

export function DeleteFolder(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolder'](arg1, arg2);
}

export function DeleteFolderRecoverable(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolderRecoverable'](arg1, arg2);
}

export function DeleteGlobalEnvironment(arg1, arg2) {
  return window['go']['main']['App']['DeleteGlobalEnvironment'](arg1, arg2);
}

export function DeleteRequest(arg1, arg2) {
  return window['go']['main']['App']['DeleteRequest'](arg1, arg2);
}

export function DeleteRequestRecoverable(arg1, arg2) {
  return window['go']['main']['App']['DeleteRequestRecoverable'](arg1, arg2);
}

export function DeleteResponseExample(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteResponseExample'](arg1, arg2, arg3);
}

export function DiscardRecoveryEntry(arg1) {
  return window['go']['main']['App']['DiscardRecoveryEntry'](arg1);
}

export function DiscardRequestDraft(arg1, arg2) {
  return window['go']['main']['App']['DiscardRequestDraft'](arg1, arg2);
}

export function DiscardUnsavedDrafts(arg1) {
  return window['go']['main']['App']['DiscardUnsavedDrafts'](arg1);
}

export function DisconnectCollectionGitRemote(arg1) {
  return window['go']['main']['App']['DisconnectCollectionGitRemote'](arg1);
}

export function DisconnectOpenAPISync(arg1) {
  return window['go']['main']['App']['DisconnectOpenAPISync'](arg1);
}

export function DisconnectWebSocket(arg1, arg2) {
  return window['go']['main']['App']['DisconnectWebSocket'](arg1, arg2);
}

export function EndGRPCStream(arg1, arg2) {
  return window['go']['main']['App']['EndGRPCStream'](arg1, arg2);
}

export function ExportCollection(arg1) {
  return window['go']['main']['App']['ExportCollection'](arg1);
}

export function ExportCollectionWithOptions(arg1, arg2) {
  return window['go']['main']['App']['ExportCollectionWithOptions'](arg1, arg2);
}

export function ExportGlobalEnvironment(arg1, arg2) {
  return window['go']['main']['App']['ExportGlobalEnvironment'](arg1, arg2);
}

export function ExportGlobalEnvironments(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportGlobalEnvironments'](arg1, arg2, arg3);
}

export function FetchCollectionGit(arg1, arg2) {
  return window['go']['main']['App']['FetchCollectionGit'](arg1, arg2);
}

export function FlushPendingWrites() {
  return window['go']['main']['App']['FlushPendingWrites']();
}

export function GenerateCollectionDocs(arg1, arg2) {
  return window['go']['main']['App']['GenerateCollectionDocs'](arg1, arg2);
}

export function GenerateGRPCMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateGRPCMessage'](arg1, arg2, arg3, arg4);
}

export function GenerateGrpcurlCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateGrpcurlCommand'](arg1, arg2, arg3);
}

export function GenerateRequestCode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateRequestCode'](arg1, arg2, arg3, arg4);
}

export function GenerateResponseExampleCode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateResponseExampleCode'](arg1, arg2, arg3, arg4);
}

export function GetCollectionGitDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCollectionGitDiff'](arg1, arg2, arg3);
}

export function GetCollectionGitStatus(arg1) {
  return window['go']['main']['App']['GetCollectionGitStatus'](arg1);
}

export function GetDevToolsSnapshot() {
  return window['go']['main']['App']['GetDevToolsSnapshot']();
}

export function GetFileCacheSize() {
  return window['go']['main']['App']['GetFileCacheSize']();
}

export function GetOpenAPISyncSpec(arg1) {
  return window['go']['main']['App']['GetOpenAPISyncSpec'](arg1);
}

export function GetOpenAPISyncSpecDiff(arg1, arg2) {
  return window['go']['main']['App']['GetOpenAPISyncSpecDiff'](arg1, arg2);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetTerminalSession(arg1) {
  return window['go']['main']['App']['GetTerminalSession'](arg1);
}

export function GetWebStorageScope() {
  return window['go']['main']['App']['GetWebStorageScope']();
}

export function GitVersion() {
  return window['go']['main']['App']['GitVersion']();
}

export function ImportCollection(arg1, arg2) {
  return window['go']['main']['App']['ImportCollection'](arg1, arg2);
}

export function ImportGlobalEnvironment(arg1, arg2) {
  return window['go']['main']['App']['ImportGlobalEnvironment'](arg1, arg2);
}

export function InitializeCollectionGit(arg1) {
  return window['go']['main']['App']['InitializeCollectionGit'](arg1);
}

export function KillTerminalSession(arg1) {
  return window['go']['main']['App']['KillTerminalSession'](arg1);
}

export function ListDotEnvFiles(arg1, arg2) {
  return window['go']['main']['App']['ListDotEnvFiles'](arg1, arg2);
}

export function ListGRPCMethods(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListGRPCMethods'](arg1, arg2, arg3);
}

export function ListRecoveryEntries() {
  return window['go']['main']['App']['ListRecoveryEntries']();
}

export function ListTerminalSessions() {
  return window['go']['main']['App']['ListTerminalSessions']();
}

export function ListUnsavedDrafts() {
  return window['go']['main']['App']['ListUnsavedDrafts']();
}

export function ListWorkspaceWindowTargets() {
  return window['go']['main']['App']['ListWorkspaceWindowTargets']();
}

export function MarkAllNotificationsRead() {
  return window['go']['main']['App']['MarkAllNotificationsRead']();
}

export function MarkNotificationRead(arg1) {
  return window['go']['main']['App']['MarkNotificationRead'](arg1);
}

export function MoveOpenTab(arg1, arg2) {
  return window['go']['main']['App']['MoveOpenTab'](arg1, arg2);
}

export function MoveOpenTabNarrow(arg1, arg2) {
  return window['go']['main']['App']['MoveOpenTabNarrow'](arg1, arg2);
}

export function OpenCollection(arg1, arg2) {
  return window['go']['main']['App']['OpenCollection'](arg1, arg2);
}

export function OpenGitCollections(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenGitCollections'](arg1, arg2, arg3);
}

export function OpenNewWindow() {
  return window['go']['main']['App']['OpenNewWindow']();
}

export function OpenRequestTab(arg1, arg2) {
  return window['go']['main']['App']['OpenRequestTab'](arg1, arg2);
}

export function OpenResponseExampleTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenResponseExampleTab'](arg1, arg2, arg3);
}

export function OpenWorkspaceInNewWindow(arg1) {
  return window['go']['main']['App']['OpenWorkspaceInNewWindow'](arg1);
}

export function ParseBru(arg1) {
  return window['go']['main']['App']['ParseBru'](arg1);
}

export function PreviewCollectionImport(arg1) {
  return window['go']['main']['App']['PreviewCollectionImport'](arg1);
}

export function PullCollectionGit(arg1, arg2, arg3) {
  return window['go']['main']['App']['PullCollectionGit'](arg1, arg2, arg3);
}

export function PushCollectionGit(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PushCollectionGit'](arg1, arg2, arg3, arg4);
}

export function ReadResponseBody(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadResponseBody'](arg1, arg2, arg3);
}

export function RefreshChangedCollections() {
  return window['go']['main']['App']['RefreshChangedCollections']();
}

export function RefreshCollection(arg1) {
  return window['go']['main']['App']['RefreshCollection'](arg1);
}

export function RemoveCollection(arg1) {
  return window['go']['main']['App']['RemoveCollection'](arg1);
}

export function RemoveCollectionRecoverable(arg1) {
  return window['go']['main']['App']['RemoveCollectionRecoverable'](arg1);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function RenameFolder(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2, arg3, arg4);
}

export function RenameRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RenameRequest'](arg1, arg2, arg3, arg4);
}

export function RenameResponseExample(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RenameResponseExample'](arg1, arg2, arg3, arg4);
}

export function ReopenLastClosedTab(arg1) {
  return window['go']['main']['App']['ReopenLastClosedTab'](arg1);
}

export function ResetDemoData() {
  return window['go']['main']['App']['ResetDemoData']();
}

export function ResizeTerminalSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminalSession'](arg1, arg2, arg3);
}

export function ResolveCollectionFolderPath(arg1, arg2) {
  return window['go']['main']['App']['ResolveCollectionFolderPath'](arg1, arg2);
}

export function ResolveProcessEnvValues(arg1, arg2) {
  return window['go']['main']['App']['ResolveProcessEnvValues'](arg1, arg2);
}

export function RestoreRecoveryEntry(arg1) {
  return window['go']['main']['App']['RestoreRecoveryEntry'](arg1);
}

export function RevealCollectionFolderInFolder(arg1, arg2) {
  return window['go']['main']['App']['RevealCollectionFolderInFolder'](arg1, arg2);
}

export function RevealCollectionInFolder(arg1) {
  return window['go']['main']['App']['RevealCollectionInFolder'](arg1);
}

export function RevealRequestInFolder(arg1, arg2) {
  return window['go']['main']['App']['RevealRequestInFolder'](arg1, arg2);
}

export function RunCollection(arg1, arg2) {
  return window['go']['main']['App']['RunCollection'](arg1, arg2);
}

export function RunCollectionWithOptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCollectionWithOptions'](arg1, arg2, arg3);
}

export function SaveAllTabs(arg1) {
  return window['go']['main']['App']['SaveAllTabs'](arg1);
}

export function SaveCollectionExport(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCollectionExport'](arg1, arg2, arg3);
}

export function SaveCookie(arg1) {
  return window['go']['main']['App']['SaveCookie'](arg1);
}

export function SaveDotEnvFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveDotEnvFile'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveGlobalEnvironmentExport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveGlobalEnvironmentExport'](arg1, arg2, arg3, arg4);
}

export function SaveRequest(arg1, arg2) {
  return window['go']['main']['App']['SaveRequest'](arg1, arg2);
}

export function SaveResponseBody(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveResponseBody'](arg1, arg2, arg3);
}

export function SaveResponseExample(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveResponseExample'](arg1, arg2, arg3);
}

export function SaveResponseTimeline(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveResponseTimeline'](arg1, arg2, arg3);
}

export function SaveUnsavedDrafts(arg1) {
  return window['go']['main']['App']['SaveUnsavedDrafts'](arg1);
}

export function ScanGitCollections(arg1) {
  return window['go']['main']['App']['ScanGitCollections'](arg1);
}

export function SelectCustomCaCertificate() {
  return window['go']['main']['App']['SelectCustomCaCertificate']();
}

export function SelectDefaultLocation() {
  return window['go']['main']['App']['SelectDefaultLocation']();
}

export function SelectRunnerDataFile() {
  return window['go']['main']['App']['SelectRunnerDataFile']();
}

export function SendGRPCStreamMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendGRPCStreamMessage'](arg1, arg2, arg3, arg4);
}

export function SendGRPCStreamMessageWithPromptValues(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendGRPCStreamMessageWithPromptValues'](arg1, arg2, arg3, arg4, arg5);
}

export function SendRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2, arg3);
}

export function SendRequestWithPromptValues(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendRequestWithPromptValues'](arg1, arg2, arg3, arg4);
}

export function SendWebSocketMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendWebSocketMessage'](arg1, arg2, arg3, arg4);
}

export function SendWebSocketMessageWithPromptValues(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendWebSocketMessageWithPromptValues'](arg1, arg2, arg3, arg4, arg5);
}

export function SetActiveGlobalEnvironment(arg1, arg2) {
  return window['go']['main']['App']['SetActiveGlobalEnvironment'](arg1, arg2);
}

export function SetActiveTab(arg1) {
  return window['go']['main']['App']['SetActiveTab'](arg1);
}

export function SetActiveTabNarrow(arg1) {
  return window['go']['main']['App']['SetActiveTabNarrow'](arg1);
}

export function SetActiveWorkspace(arg1) {
  return window['go']['main']['App']['SetActiveWorkspace'](arg1);
}

export function SetCollectionGitRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCollectionGitRemote'](arg1, arg2, arg3);
}

export function StageCollectionGitPaths(arg1, arg2) {
  return window['go']['main']['App']['StageCollectionGitPaths'](arg1, arg2);
}

export function StringifyBru(arg1) {
  return window['go']['main']['App']['StringifyBru'](arg1);
}

export function UnstageCollectionGitPaths(arg1, arg2) {
  return window['go']['main']['App']['UnstageCollectionGitPaths'](arg1, arg2);
}

export function UpdateCollectionAuth(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollectionAuth'](arg1, arg2);
}

export function UpdateCollectionClientCertificates(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollectionClientCertificates'](arg1, arg2);
}

export function UpdateCollectionDocs(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollectionDocs'](arg1, arg2);
}

export function UpdateCollectionHeaders(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollectionHeaders'](arg1, arg2);
}

export function UpdateCollectionPresets(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollectionPresets'](arg1, arg2);
}

export function UpdateCollectionProtobuf(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollectionProtobuf'](arg1, arg2);
}

export function UpdateCollectionProxy(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollectionProxy'](arg1, arg2);
}

export function UpdateCollectionScripts(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateCollectionScripts'](arg1, arg2, arg3, arg4);
}

export function UpdateCollectionSecurityConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollectionSecurityConfig'](arg1, arg2);
}

export function UpdateCollectionVariables(arg1, arg2) {
  return window['go']['main']['App']['UpdateCollectionVariables'](arg1, arg2);
}

export function UpdateEnvironmentVariables(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateEnvironmentVariables'](arg1, arg2, arg3);
}

export function UpdateFolderSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateFolderSettings'](arg1, arg2, arg3);
}

export function UpdateGlobalEnvironment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateGlobalEnvironment'](arg1, arg2, arg3, arg4);
}

export function UpdateGlobalEnvironmentVariables(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateGlobalEnvironmentVariables'](arg1, arg2, arg3);
}

export function UpdateOpenAPISyncConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateOpenAPISyncConfig'](arg1, arg2);
}

export function UpdateOpenTabPanes(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateOpenTabPanes'](arg1, arg2, arg3);
}

export function UpdateOpenTabPanesNarrow(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateOpenTabPanesNarrow'](arg1, arg2, arg3);
}

export function UpdatePreferences(arg1) {
  return window['go']['main']['App']['UpdatePreferences'](arg1);
}

export function UpdateRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateRequest'](arg1, arg2, arg3);
}

export function UpdateRequestNarrow(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateRequestNarrow'](arg1, arg2, arg3);
}

export function UpdateResponseExample(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateResponseExample'](arg1, arg2, arg3, arg4);
}

export function VisualizerDocument(arg1, arg2) {
  return window['go']['main']['App']['VisualizerDocument'](arg1, arg2);
}

export function WriteTerminalSession(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminalSession'](arg1, arg2);
}
